//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueba.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLExpress;Initial Catalog=BDProyectoWeb;Integrated Securit" +
            "y=True;TrustServerCertificate=True")]
        public string BDProyectoWebConnectionString {
            get {
                return ((string)(this["BDProyectoWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLExpress;Initial Catalog=BDProyectoWeb;Integrated Securit" +
            "y=True;Encrypt=True;TrustServerCertificate=True")]
        public string BDProyectoWebConnectionString1 {
            get {
                return ((string)(this["BDProyectoWebConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\PCDaniel2;Initial Catalog=BDProyectoWeb;Integrated Security" +
            "=True;TrustServerCertificate=True")]
        public string BDProyectoWebConnectionString2 {
            get {
                return ((string)(this["BDProyectoWebConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\\SQLExpress;Initial Catalog=BDProyectoWeb2;Integrated Securi" +
            "ty=True;TrustServerCertificate=True")]
        public string BDProyectoWeb2ConnectionString {
            get {
                return ((string)(this["BDProyectoWeb2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=adriserver3003.database.windows.net;Initial Catalog=ProyectoDB;User I" +
            "D=adrianadv;Password=ADV_300305_azure;TrustServerCertificate=True")]
        public string ProyectoDBConnectionString {
            get {
                return ((string)(this["ProyectoDBConnectionString"]));
            }
        }
    }
}
